# Generated by Django 4.2.1 on 2024-09-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
