# Generated by Django 4.2.1 on 2024-09-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_time_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-time_create']},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Важно'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='time_done',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название заметки'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['-time_create'], name='todo_todo_time_cr_b0762d_idx'),
        ),
    ]
